// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: whitelist/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgMembershipApplication struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *MsgMembershipApplication) Reset()         { *m = MsgMembershipApplication{} }
func (m *MsgMembershipApplication) String() string { return proto.CompactTextString(m) }
func (*MsgMembershipApplication) ProtoMessage()    {}
func (*MsgMembershipApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{0}
}
func (m *MsgMembershipApplication) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMembershipApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMembershipApplication.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMembershipApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMembershipApplication.Merge(m, src)
}
func (m *MsgMembershipApplication) XXX_Size() int {
	return m.Size()
}
func (m *MsgMembershipApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMembershipApplication.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMembershipApplication proto.InternalMessageInfo

func (m *MsgMembershipApplication) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgMembershipApplication) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MsgMembershipApplicationResponse struct {
	Joined bool `protobuf:"varint,1,opt,name=joined,proto3" json:"joined,omitempty"`
}

func (m *MsgMembershipApplicationResponse) Reset()         { *m = MsgMembershipApplicationResponse{} }
func (m *MsgMembershipApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMembershipApplicationResponse) ProtoMessage()    {}
func (*MsgMembershipApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{1}
}
func (m *MsgMembershipApplicationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMembershipApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMembershipApplicationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMembershipApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMembershipApplicationResponse.Merge(m, src)
}
func (m *MsgMembershipApplicationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMembershipApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMembershipApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMembershipApplicationResponse proto.InternalMessageInfo

func (m *MsgMembershipApplicationResponse) GetJoined() bool {
	if m != nil {
		return m.Joined
	}
	return false
}

type MsgBuyerApplication struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ContactInfo string `protobuf:"bytes,2,opt,name=contactInfo,proto3" json:"contactInfo,omitempty"`
}

func (m *MsgBuyerApplication) Reset()         { *m = MsgBuyerApplication{} }
func (m *MsgBuyerApplication) String() string { return proto.CompactTextString(m) }
func (*MsgBuyerApplication) ProtoMessage()    {}
func (*MsgBuyerApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{2}
}
func (m *MsgBuyerApplication) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuyerApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuyerApplication.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuyerApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuyerApplication.Merge(m, src)
}
func (m *MsgBuyerApplication) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuyerApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuyerApplication.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuyerApplication proto.InternalMessageInfo

func (m *MsgBuyerApplication) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgBuyerApplication) GetContactInfo() string {
	if m != nil {
		return m.ContactInfo
	}
	return ""
}

type MsgBuyerApplicationResponse struct {
	BuyerId uint64 `protobuf:"varint,1,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
}

func (m *MsgBuyerApplicationResponse) Reset()         { *m = MsgBuyerApplicationResponse{} }
func (m *MsgBuyerApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBuyerApplicationResponse) ProtoMessage()    {}
func (*MsgBuyerApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{3}
}
func (m *MsgBuyerApplicationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuyerApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuyerApplicationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuyerApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuyerApplicationResponse.Merge(m, src)
}
func (m *MsgBuyerApplicationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuyerApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuyerApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuyerApplicationResponse proto.InternalMessageInfo

func (m *MsgBuyerApplicationResponse) GetBuyerId() uint64 {
	if m != nil {
		return m.BuyerId
	}
	return 0
}

type MsgSellerApplication struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ContactInfo string `protobuf:"bytes,2,opt,name=contactInfo,proto3" json:"contactInfo,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *MsgSellerApplication) Reset()         { *m = MsgSellerApplication{} }
func (m *MsgSellerApplication) String() string { return proto.CompactTextString(m) }
func (*MsgSellerApplication) ProtoMessage()    {}
func (*MsgSellerApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{4}
}
func (m *MsgSellerApplication) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSellerApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSellerApplication.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSellerApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSellerApplication.Merge(m, src)
}
func (m *MsgSellerApplication) XXX_Size() int {
	return m.Size()
}
func (m *MsgSellerApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSellerApplication.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSellerApplication proto.InternalMessageInfo

func (m *MsgSellerApplication) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSellerApplication) GetContactInfo() string {
	if m != nil {
		return m.ContactInfo
	}
	return ""
}

func (m *MsgSellerApplication) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MsgSellerApplicationResponse struct {
	SellerId uint64 `protobuf:"varint,1,opt,name=sellerId,proto3" json:"sellerId,omitempty"`
}

func (m *MsgSellerApplicationResponse) Reset()         { *m = MsgSellerApplicationResponse{} }
func (m *MsgSellerApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSellerApplicationResponse) ProtoMessage()    {}
func (*MsgSellerApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{5}
}
func (m *MsgSellerApplicationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSellerApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSellerApplicationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSellerApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSellerApplicationResponse.Merge(m, src)
}
func (m *MsgSellerApplicationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSellerApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSellerApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSellerApplicationResponse proto.InternalMessageInfo

func (m *MsgSellerApplicationResponse) GetSellerId() uint64 {
	if m != nil {
		return m.SellerId
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgMembershipApplication)(nil), "zeta.whitelist.MsgMembershipApplication")
	proto.RegisterType((*MsgMembershipApplicationResponse)(nil), "zeta.whitelist.MsgMembershipApplicationResponse")
	proto.RegisterType((*MsgBuyerApplication)(nil), "zeta.whitelist.MsgBuyerApplication")
	proto.RegisterType((*MsgBuyerApplicationResponse)(nil), "zeta.whitelist.MsgBuyerApplicationResponse")
	proto.RegisterType((*MsgSellerApplication)(nil), "zeta.whitelist.MsgSellerApplication")
	proto.RegisterType((*MsgSellerApplicationResponse)(nil), "zeta.whitelist.MsgSellerApplicationResponse")
}

func init() { proto.RegisterFile("whitelist/tx.proto", fileDescriptor_3bd336a39a8c9db2) }

var fileDescriptor_3bd336a39a8c9db2 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xb1, 0x4f, 0xc2, 0x40,
	0x14, 0xc6, 0x29, 0x10, 0xc0, 0x67, 0x62, 0xf4, 0x54, 0xd2, 0x54, 0xd3, 0x90, 0xea, 0x40, 0xa2,
	0x29, 0x44, 0x07, 0x13, 0x37, 0x99, 0x64, 0xe8, 0x60, 0xdd, 0xdc, 0x4a, 0x79, 0x94, 0x9a, 0x72,
	0x77, 0xe9, 0x9d, 0x11, 0xfc, 0x2b, 0xfc, 0xb3, 0x74, 0x63, 0x74, 0x34, 0xf0, 0x8f, 0x18, 0x2a,
	0x5c, 0xc0, 0x96, 0xa4, 0x83, 0xdb, 0x7d, 0xf7, 0xbe, 0x7c, 0xef, 0x97, 0xfb, 0x72, 0x40, 0x5e,
	0x87, 0xa1, 0xc4, 0x28, 0x14, 0xb2, 0x25, 0xc7, 0x36, 0x8f, 0x99, 0x64, 0x64, 0xef, 0x0d, 0xa5,
	0x67, 0xab, 0x81, 0x75, 0x0f, 0xba, 0x23, 0x02, 0x07, 0x47, 0x3d, 0x8c, 0xc5, 0x30, 0xe4, 0x77,
	0x9c, 0x47, 0xa1, 0xef, 0xc9, 0x90, 0x51, 0xa2, 0x43, 0xd5, 0x8f, 0xd1, 0x93, 0x2c, 0xd6, 0xb5,
	0x86, 0xd6, 0xdc, 0x71, 0x57, 0x92, 0x10, 0x28, 0x53, 0x6f, 0x84, 0x7a, 0x31, 0xb9, 0x4e, 0xce,
	0xd6, 0x2d, 0x34, 0xb6, 0x25, 0xb9, 0x28, 0x38, 0xa3, 0x02, 0x49, 0x1d, 0x2a, 0xcf, 0x2c, 0xa4,
	0xd8, 0x4f, 0x02, 0x6b, 0xee, 0x52, 0x59, 0x0f, 0x70, 0xe8, 0x88, 0xa0, 0xf3, 0x32, 0xc1, 0x38,
	0x1f, 0x40, 0x03, 0x76, 0x7d, 0x46, 0xa5, 0xe7, 0xcb, 0x2e, 0x1d, 0xb0, 0x25, 0xc7, 0xfa, 0x95,
	0x75, 0x03, 0x27, 0x19, 0x91, 0x8a, 0x44, 0x87, 0x6a, 0x6f, 0x31, 0xeb, 0xfe, 0xa2, 0x94, 0xdd,
	0x95, 0xb4, 0x06, 0x70, 0xe4, 0x88, 0xe0, 0x11, 0xa3, 0xe8, 0xdf, 0x60, 0xd4, 0x7b, 0x95, 0x36,
	0xde, 0xeb, 0x34, 0x6b, 0x8f, 0x22, 0x34, 0xa0, 0x26, 0x92, 0xa1, 0x42, 0x54, 0xfa, 0xea, 0xb3,
	0x08, 0x25, 0x47, 0x04, 0x44, 0xc0, 0x71, 0x76, 0x75, 0x4d, 0x7b, 0xb3, 0x67, 0x7b, 0x5b, 0x35,
	0x46, 0x3b, 0xaf, 0x53, 0x81, 0xf5, 0x61, 0x3f, 0xd5, 0xd4, 0x59, 0x46, 0xca, 0x5f, 0x93, 0x71,
	0x91, 0xc3, 0xa4, 0xb6, 0x04, 0x70, 0x90, 0xee, 0xe0, 0x3c, 0x23, 0x21, 0xe5, 0x32, 0x2e, 0xf3,
	0xb8, 0x56, 0x8b, 0x3a, 0xed, 0x8f, 0x99, 0xa9, 0x4d, 0x67, 0xa6, 0xf6, 0x3d, 0x33, 0xb5, 0xf7,
	0xb9, 0x59, 0x98, 0xce, 0xcd, 0xc2, 0xd7, 0xdc, 0x2c, 0x3c, 0xd5, 0x17, 0x31, 0xad, 0x71, 0x6b,
	0xed, 0x1b, 0x4d, 0x38, 0x8a, 0x5e, 0x25, 0xf9, 0x4a, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd3, 0x53, 0x66, 0x03, 0x60, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	MembershipApplication(ctx context.Context, in *MsgMembershipApplication, opts ...grpc.CallOption) (*MsgMembershipApplicationResponse, error)
	BuyerApplication(ctx context.Context, in *MsgBuyerApplication, opts ...grpc.CallOption) (*MsgBuyerApplicationResponse, error)
	SellerApplication(ctx context.Context, in *MsgSellerApplication, opts ...grpc.CallOption) (*MsgSellerApplicationResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) MembershipApplication(ctx context.Context, in *MsgMembershipApplication, opts ...grpc.CallOption) (*MsgMembershipApplicationResponse, error) {
	out := new(MsgMembershipApplicationResponse)
	err := c.cc.Invoke(ctx, "/zeta.whitelist.Msg/MembershipApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BuyerApplication(ctx context.Context, in *MsgBuyerApplication, opts ...grpc.CallOption) (*MsgBuyerApplicationResponse, error) {
	out := new(MsgBuyerApplicationResponse)
	err := c.cc.Invoke(ctx, "/zeta.whitelist.Msg/BuyerApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SellerApplication(ctx context.Context, in *MsgSellerApplication, opts ...grpc.CallOption) (*MsgSellerApplicationResponse, error) {
	out := new(MsgSellerApplicationResponse)
	err := c.cc.Invoke(ctx, "/zeta.whitelist.Msg/SellerApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	MembershipApplication(context.Context, *MsgMembershipApplication) (*MsgMembershipApplicationResponse, error)
	BuyerApplication(context.Context, *MsgBuyerApplication) (*MsgBuyerApplicationResponse, error)
	SellerApplication(context.Context, *MsgSellerApplication) (*MsgSellerApplicationResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) MembershipApplication(ctx context.Context, req *MsgMembershipApplication) (*MsgMembershipApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MembershipApplication not implemented")
}
func (*UnimplementedMsgServer) BuyerApplication(ctx context.Context, req *MsgBuyerApplication) (*MsgBuyerApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyerApplication not implemented")
}
func (*UnimplementedMsgServer) SellerApplication(ctx context.Context, req *MsgSellerApplication) (*MsgSellerApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellerApplication not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_MembershipApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMembershipApplication)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MembershipApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zeta.whitelist.Msg/MembershipApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MembershipApplication(ctx, req.(*MsgMembershipApplication))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BuyerApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBuyerApplication)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BuyerApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zeta.whitelist.Msg/BuyerApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BuyerApplication(ctx, req.(*MsgBuyerApplication))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SellerApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSellerApplication)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SellerApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zeta.whitelist.Msg/SellerApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SellerApplication(ctx, req.(*MsgSellerApplication))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zeta.whitelist.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MembershipApplication",
			Handler:    _Msg_MembershipApplication_Handler,
		},
		{
			MethodName: "BuyerApplication",
			Handler:    _Msg_BuyerApplication_Handler,
		},
		{
			MethodName: "SellerApplication",
			Handler:    _Msg_SellerApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whitelist/tx.proto",
}

func (m *MsgMembershipApplication) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMembershipApplication) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMembershipApplication) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMembershipApplicationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMembershipApplicationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMembershipApplicationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Joined {
		i--
		if m.Joined {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgBuyerApplication) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuyerApplication) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuyerApplication) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContactInfo) > 0 {
		i -= len(m.ContactInfo)
		copy(dAtA[i:], m.ContactInfo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContactInfo)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBuyerApplicationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuyerApplicationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuyerApplicationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BuyerId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BuyerId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSellerApplication) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSellerApplication) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSellerApplication) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ContactInfo) > 0 {
		i -= len(m.ContactInfo)
		copy(dAtA[i:], m.ContactInfo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContactInfo)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSellerApplicationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSellerApplicationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSellerApplicationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SellerId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SellerId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgMembershipApplication) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgMembershipApplicationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Joined {
		n += 2
	}
	return n
}

func (m *MsgBuyerApplication) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContactInfo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBuyerApplicationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BuyerId != 0 {
		n += 1 + sovTx(uint64(m.BuyerId))
	}
	return n
}

func (m *MsgSellerApplication) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContactInfo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSellerApplicationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SellerId != 0 {
		n += 1 + sovTx(uint64(m.SellerId))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgMembershipApplication) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMembershipApplication: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMembershipApplication: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMembershipApplicationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMembershipApplicationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMembershipApplicationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Joined", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Joined = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuyerApplication) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuyerApplication: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuyerApplication: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContactInfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContactInfo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuyerApplicationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuyerApplicationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuyerApplicationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerId", wireType)
			}
			m.BuyerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BuyerId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSellerApplication) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSellerApplication: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSellerApplication: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContactInfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContactInfo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSellerApplicationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSellerApplicationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSellerApplicationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellerId", wireType)
			}
			m.SellerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SellerId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
