accounts:
  - name: alice
    coins: ["20000token", "200000000stake", "1000crow"]
  - name: bob
    coins: ["10000token", "100000000stake", "1000crow"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
