// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: escrow/crow.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Crow struct {
	CrowId     uint64     `protobuf:"varint,1,opt,name=crowId,proto3" json:"crowId,omitempty"`
	BuyOrderId uint64     `protobuf:"varint,2,opt,name=buyOrderId,proto3" json:"buyOrderId,omitempty"`
	DisputeId  uint64     `protobuf:"varint,3,opt,name=disputeId,proto3" json:"disputeId,omitempty"`
	VerdictId  uint64     `protobuf:"varint,4,opt,name=verdictId,proto3" json:"verdictId,omitempty"`
	Amount     types.Coin `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount"`
	SellerCol  types.Coin `protobuf:"bytes,6,opt,name=sellerCol,proto3" json:"sellerCol"`
	BuyerCol   types.Coin `protobuf:"bytes,7,opt,name=buyerCol,proto3" json:"buyerCol"`
	Status     string     `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *Crow) Reset()         { *m = Crow{} }
func (m *Crow) String() string { return proto.CompactTextString(m) }
func (*Crow) ProtoMessage()    {}
func (*Crow) Descriptor() ([]byte, []int) {
	return fileDescriptor_e183fe88f92613f0, []int{0}
}
func (m *Crow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Crow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Crow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Crow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Crow.Merge(m, src)
}
func (m *Crow) XXX_Size() int {
	return m.Size()
}
func (m *Crow) XXX_DiscardUnknown() {
	xxx_messageInfo_Crow.DiscardUnknown(m)
}

var xxx_messageInfo_Crow proto.InternalMessageInfo

func (m *Crow) GetCrowId() uint64 {
	if m != nil {
		return m.CrowId
	}
	return 0
}

func (m *Crow) GetBuyOrderId() uint64 {
	if m != nil {
		return m.BuyOrderId
	}
	return 0
}

func (m *Crow) GetDisputeId() uint64 {
	if m != nil {
		return m.DisputeId
	}
	return 0
}

func (m *Crow) GetVerdictId() uint64 {
	if m != nil {
		return m.VerdictId
	}
	return 0
}

func (m *Crow) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *Crow) GetSellerCol() types.Coin {
	if m != nil {
		return m.SellerCol
	}
	return types.Coin{}
}

func (m *Crow) GetBuyerCol() types.Coin {
	if m != nil {
		return m.BuyerCol
	}
	return types.Coin{}
}

func (m *Crow) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Crow)(nil), "zeta.escrow.Crow")
}

func init() { proto.RegisterFile("escrow/crow.proto", fileDescriptor_e183fe88f92613f0) }

var fileDescriptor_e183fe88f92613f0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe3, 0x12, 0x42, 0xeb, 0x4e, 0x18, 0x84, 0x4c, 0x85, 0x4c, 0xc5, 0xd4, 0x05, 0x5b,
	0x85, 0x81, 0x01, 0xb1, 0xb4, 0x53, 0x26, 0xa4, 0x8e, 0x6c, 0x49, 0x6c, 0x55, 0x91, 0xda, 0x5e,
	0x65, 0x3b, 0x2d, 0xe5, 0x29, 0x78, 0x2b, 0x3a, 0x76, 0x64, 0x42, 0x28, 0x79, 0x11, 0xe4, 0x38,
	0x6a, 0x19, 0xbb, 0x58, 0xbe, 0xff, 0xbf, 0xef, 0xf4, 0xeb, 0x0e, 0x9f, 0x2b, 0x93, 0x69, 0x58,
	0x0b, 0xf7, 0xf0, 0xa5, 0x06, 0x0b, 0xa4, 0xfb, 0xa1, 0x6c, 0xc2, 0xbd, 0xde, 0xbb, 0x9c, 0xc2,
	0x14, 0x6a, 0x5d, 0xb8, 0x9f, 0x6f, 0xe9, 0xb1, 0x0c, 0xcc, 0x1c, 0x8c, 0x48, 0x13, 0xa3, 0xc4,
	0x6a, 0x98, 0x2a, 0x9b, 0x0c, 0x45, 0x06, 0xf9, 0xc2, 0xfb, 0x77, 0x5f, 0x2d, 0x1c, 0x8e, 0x35,
	0xac, 0xc9, 0x15, 0x8e, 0xdc, 0x98, 0x58, 0x52, 0xd4, 0x47, 0x83, 0x70, 0xd2, 0x54, 0x84, 0x61,
	0x9c, 0x16, 0x9b, 0x57, 0x2d, 0x95, 0x8e, 0x25, 0x6d, 0xd5, 0xde, 0x3f, 0x85, 0xdc, 0xe0, 0x8e,
	0xcc, 0xcd, 0xb2, 0xb0, 0x2a, 0x96, 0xf4, 0xa4, 0xb6, 0x0f, 0x82, 0x73, 0x57, 0x4a, 0xcb, 0x3c,
	0xb3, 0xb1, 0xa4, 0xa1, 0x77, 0xf7, 0x02, 0x79, 0xc2, 0x51, 0x32, 0x87, 0x62, 0x61, 0xe9, 0x69,
	0x1f, 0x0d, 0xba, 0x0f, 0xd7, 0xdc, 0xa7, 0xe5, 0x2e, 0x2d, 0x6f, 0xd2, 0xf2, 0x31, 0xe4, 0x8b,
	0x51, 0xb8, 0xfd, 0xb9, 0x0d, 0x26, 0x4d, 0x3b, 0x79, 0xc1, 0x1d, 0xa3, 0x66, 0x33, 0xa5, 0xc7,
	0x30, 0xa3, 0xd1, 0x71, 0xec, 0x81, 0x20, 0xcf, 0xb8, 0x9d, 0x16, 0x1b, 0x4f, 0x9f, 0x1d, 0x47,
	0xef, 0x01, 0xb7, 0x28, 0x63, 0x13, 0x5b, 0x18, 0xda, 0xee, 0xa3, 0x41, 0x67, 0xd2, 0x54, 0xa3,
	0xfb, 0x6d, 0xc9, 0xd0, 0xae, 0x64, 0xe8, 0xb7, 0x64, 0xe8, 0xb3, 0x62, 0xc1, 0xae, 0x62, 0xc1,
	0x77, 0xc5, 0x82, 0xb7, 0x0b, 0x77, 0x26, 0xf1, 0x2e, 0x9a, 0x03, 0xda, 0xcd, 0x52, 0x99, 0x34,
	0xaa, 0xf7, 0xff, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xdb, 0x80, 0x3b, 0xd7, 0x01, 0x00,
	0x00,
}

func (m *Crow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Crow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Crow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintCrow(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x42
	}
	{
		size, err := m.BuyerCol.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCrow(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.SellerCol.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCrow(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCrow(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.VerdictId != 0 {
		i = encodeVarintCrow(dAtA, i, uint64(m.VerdictId))
		i--
		dAtA[i] = 0x20
	}
	if m.DisputeId != 0 {
		i = encodeVarintCrow(dAtA, i, uint64(m.DisputeId))
		i--
		dAtA[i] = 0x18
	}
	if m.BuyOrderId != 0 {
		i = encodeVarintCrow(dAtA, i, uint64(m.BuyOrderId))
		i--
		dAtA[i] = 0x10
	}
	if m.CrowId != 0 {
		i = encodeVarintCrow(dAtA, i, uint64(m.CrowId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCrow(dAtA []byte, offset int, v uint64) int {
	offset -= sovCrow(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Crow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CrowId != 0 {
		n += 1 + sovCrow(uint64(m.CrowId))
	}
	if m.BuyOrderId != 0 {
		n += 1 + sovCrow(uint64(m.BuyOrderId))
	}
	if m.DisputeId != 0 {
		n += 1 + sovCrow(uint64(m.DisputeId))
	}
	if m.VerdictId != 0 {
		n += 1 + sovCrow(uint64(m.VerdictId))
	}
	l = m.Amount.Size()
	n += 1 + l + sovCrow(uint64(l))
	l = m.SellerCol.Size()
	n += 1 + l + sovCrow(uint64(l))
	l = m.BuyerCol.Size()
	n += 1 + l + sovCrow(uint64(l))
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovCrow(uint64(l))
	}
	return n
}

func sovCrow(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCrow(x uint64) (n int) {
	return sovCrow(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Crow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Crow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Crow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CrowId", wireType)
			}
			m.CrowId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CrowId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyOrderId", wireType)
			}
			m.BuyOrderId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BuyOrderId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeId", wireType)
			}
			m.DisputeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerdictId", wireType)
			}
			m.VerdictId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerdictId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCrow
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellerCol", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCrow
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SellerCol.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerCol", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCrow
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BuyerCol.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCrow(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCrow
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCrow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCrow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCrow
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCrow
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCrow
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCrow        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCrow          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCrow = fmt.Errorf("proto: unexpected end of group")
)
